---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  labels:
    app: nginx-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
        - name: nginx-hello
          image: docker.adzkia.web.id/ramadoni/nginx-hello:latest
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-hello
  labels:
    app: nginx-hello
spec:
  selector:
    app: nginx-hello
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
